question_data = {"response_code": 0,
                 "results": [
                     {"category": "Art",
                      "type": "boolean",
                      "difficulty": "easy",
                      "question": "Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Science & Nature", "type": "boolean",
                      "difficulty": "easy", "question": "An atom contains a nucleus.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "General Knowledge", "type": "boolean",
                      "difficulty": "medium",
                      "question": "The average woman is 5 inches \/ 13 centimeters shorter than the average man.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                      "question": "When BMW was established in 1916, it was producing automobiles.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "medium",
                      "question": "The Sonoran Desert is located in eastern Africa.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "History", "type": "boolean", "difficulty": "medium",
                      "question": "Abraham Lincoln was the first U.S. President to be born outside the borders of the thirteen original states. ",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Sports", "type": "boolean", "difficulty": "easy",
                      "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Music", "type": "boolean",
                      "difficulty": "easy",
                      "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Video Games", "type": "boolean",
                      "difficulty": "easy",
                      "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]}
